// src/views/backend/groups/index.vue
<!--
  放置路径：src/views/backend/groups/index.vue
  完整替换。
  职责：
  - 列表：GET /api/global/group/list（分页 + keyword + project/status 过滤）
  - 卡片网格（3列）+ 详情抽屉
  - 抽屉内：状态 toggle / 成员列表 / ContactSelector 添加成员 / 移除成员 / permissionCodes 展示
  - 新建权限组 Dialog：groupName / groupCode / project / parentGroupCode / ruleCodes 树选 / extraPermissionCodes
  - 无 router.push
-->
<template>
  <main class="pc-page pc-anim-fade">

    <!-- 工具栏 -->
    <div class="groups-toolbar">
      <el-input
        v-model="query.keyword"
        placeholder="搜索组名或编码"
        clearable
        style="width:240px"
        @change="onSearch"
      >
        <template #prefix><el-icon><Search /></el-icon></template>
      </el-input>

      <el-select v-model="query.project" placeholder="全部系统" clearable style="width:140px" @change="onSearch">
        <el-option label="全部系统" value="" />
        <el-option v-for="p in projects" :key="p" :label="p" :value="p" />
      </el-select>

      <el-select v-model="query.status" placeholder="全部状态" clearable style="width:130px" @change="onSearch">
        <el-option label="全部状态" value="" />
        <el-option label="启用" value="Active" />
        <el-option label="禁用" value="Disabled" />
      </el-select>

      <div style="margin-left:auto">
        <el-button type="primary" @click="openCreate">
          <el-icon><Plus /></el-icon> 新建权限组
        </el-button>
      </div>
    </div>

    <!-- 卡片网格 -->
    <div class="groups-grid" v-loading="loading">
      <RbacEmptyState v-if="!loading && rows.length === 0" title="暂无权限组" description="尝试调整搜索条件或新建权限组" style="grid-column:span 3" />

      <div
        v-for="g in rows" :key="g.groupCode"
        class="group-card"
        @click="openDetail(g)"
        @mouseenter="e => (e.currentTarget as HTMLElement).style.borderColor = '#cdcdd2'"
        @mouseleave="e => (e.currentTarget as HTMLElement).style.borderColor = 'var(--pc-hairline)'"
      >
        <div class="group-card__top">
          <div class="group-card__icon">
            <el-icon :size="20"><Lock /></el-icon>
          </div>
          <RbacStatusBadge :status="g.status as 'Active'|'Disabled'" size="sm" />
        </div>
        <div class="group-card__body">
          <div class="group-card__name">{{ g.groupName }}</div>
          <div class="pc-t-mono pc-t-cap" style="font-size:11.5px;margin-top:2px">{{ g.groupCode }}</div>
        </div>
        <hr class="pc-hr" />
        <div class="group-card__foot">
          <span class="group-card__proj">
            <RbacProjectGlyph :code="g.project" :name="g.project" :size="20" />
            <span class="pc-t-cap" style="font-weight:500">{{ g.project }}</span>
          </span>
          <span class="pc-t-cap">
            <b style="color:var(--pc-ink)">{{ g.memberCount ?? 0 }}</b> 成员 ·
            <b style="color:var(--pc-ink)">{{ (g.permissionCodes||[]).length }}</b> 权限码
          </span>
        </div>
      </div>
    </div>

    <!-- 分页 -->
    <div class="groups-pagination">
      <span class="pc-t-cap">显示 {{ rows.length }} 个 · 共 {{ total }} 个权限组</span>
      <el-pagination
        v-model:current-page="query.page"
        v-model:page-size="query.pageSize"
        :page-sizes="[20, 50]"
        :total="total"
        layout="sizes, prev, pager, next"
        small
        @size-change="loadGroups"
        @current-change="loadGroups"
      />
    </div>

    <!-- 接口来源 -->
    <div style="margin-top:24px">
      <RbacApiSource :endpoints="[
        { m: 'GET',    p: '/api/global/group/list',                          d: '跨 project 权限组列表（分页）' },
        { m: 'POST',   p: '/api/group',                                      d: '新建权限组（ruleCodes + extraPermissionCodes）' },
        { m: 'PUT',    p: '/api/group/{groupCode}/status',                   d: '启用 / 禁用权限组' },
        { m: 'POST',   p: '/api/global/group/{groupCode}/members',           d: '添加成员（body 含 targetProject）' },
        { m: 'DELETE', p: '/api/global/group/{groupCode}/members/{userid}',  d: '移除成员（query targetProject）' },
        { m: 'GET',    p: '/api/rule/tree',                                  d: '新建时规则授权选择器' },
        { m: 'GET',    p: '/api/api-map/list',                               d: '新建时 extraPermissionCodes 选择器' },
      ]" note="组层级仅用于展示，实际访问由 permissionCodes 决定。新建/编辑为 per-project 接口（X-Project = group.project）。" />
    </div>

    <!-- ══ 详情抽屉 ══ -->
    <el-drawer v-model="drawerVisible" direction="rtl" :size="480" :with-header="false" append-to-body>
      <div v-if="selectedGroup" class="detail-drawer">
        <!-- 头部 -->
        <div class="detail-header">
          <span class="pc-t-cap-strong">权限组详情</span>
          <el-button text @click="drawerVisible = false"><el-icon><Close /></el-icon></el-button>
        </div>

        <!-- 组信息 -->
        <div class="detail-hero">
          <div class="detail-hero__icon"><el-icon :size="24"><Lock /></el-icon></div>
          <div style="flex:1">
            <div style="display:flex;align-items:center;gap:9px">
              <span class="pc-t-section" style="font-size:21px">{{ selectedGroup.groupName }}</span>
              <RbacStatusBadge :status="selectedGroup.status as 'Active'|'Disabled'" />
            </div>
            <div class="pc-t-mono pc-t-cap" style="margin-top:2px">{{ selectedGroup.groupCode }}</div>
          </div>
        </div>

        <!-- Meta cards -->
        <div class="detail-meta-row">
          <div class="detail-meta-card">
            <div class="pc-t-cap" style="font-size:11px">所属系统</div>
            <div style="display:flex;align-items:center;gap:7px;margin-top:4px">
              <RbacProjectGlyph :code="selectedGroup.project" :name="selectedGroup.project" :size="22" />
              <span class="pc-t-body-strong" style="font-size:13px">{{ selectedGroup.project }}</span>
            </div>
          </div>
          <div class="detail-meta-card">
            <div class="pc-t-cap" style="font-size:11px">父权限组</div>
            <div class="pc-t-body-strong" style="font-size:13px;margin-top:4px">{{ selectedGroup.parent_group_code || '根组' }}</div>
          </div>
        </div>

        <div class="detail-body">
          <!-- 状态 toggle -->
          <div class="detail-section-card">
            <div>
              <div class="pc-t-body-strong" style="font-size:14px">启用状态</div>
              <div class="pc-t-cap">PUT /api/group/&#123;groupCode&#125;/status</div>
            </div>
            <el-switch
              :model-value="selectedGroup.status === 'Active'"
              :loading="statusLoading"
              @change="(v) => toggleStatus(Boolean(v))"
            />
          </div>

          <!-- 成员 -->
          <div class="detail-section-head">
            <span class="pc-t-section">成员（{{ detailMembers.length }}）</span>
            <el-button text type="primary" size="small" @click="addMemberExpanded = !addMemberExpanded">
              <el-icon><Plus /></el-icon> 添加成员
            </el-button>
          </div>

          <!-- ContactSelector 展开区 -->
          <div v-if="addMemberExpanded" class="add-member-box pc-anim-fade">
            <ContactSelector
              :org-list="MOCK_ORGS"
              :user-list="MOCK_USERS"
              :multiple="true"
              @confirm="onMemberConfirm"
              @cancel="addMemberExpanded = false"
            />
          </div>

          <div class="member-list">
            <div v-if="detailMembers.length === 0 && !membersLoading" class="pc-t-cap" style="padding:6px 0">暂无成员</div>
            <div v-loading="membersLoading">
              <div
                v-for="u in detailMembers" :key="u.userid"
                class="member-row"
              >
                <RbacAvatar :name="u.username || u.userid" :size="30" :dim="u.status === 'Disabled'" />
                <div style="flex:1;min-width:0">
                  <div class="pc-t-body-strong" style="font-size:13.5px">{{ u.username || u.userid }}</div>
                  <div class="pc-t-mono pc-t-cap" style="font-size:11px">{{ u.userid }}</div>
                </div>
                <el-button
                  text size="small"
                  style="color:var(--pc-deny);width:28px;height:28px;background:var(--pc-deny-wash);border-radius:8px"
                  @click="removeMember(u.userid)"
                >
                  <el-icon><Close /></el-icon>
                </el-button>
              </div>
            </div>
          </div>

          <!-- 权限码 -->
          <div class="detail-section-head" style="margin-top:8px">
            <span class="pc-t-section">授权权限码（{{ (selectedGroup.permissionCodes||[]).length }}）</span>
          </div>
          <div class="pc-t-cap" style="margin-bottom:12px">permissionCodes = ruleCodes 推导值 ∪ extraPermissionCodes</div>
          <div class="perm-chips">
            <span
              v-for="pc in (selectedGroup.permissionCodes||[])" :key="pc"
              class="perm-chip"
              :style="{ background: pc.startsWith('menu:') ? '#eef4fb' : '#f3eefb', color: pc.startsWith('menu:') ? 'var(--pc-blue)' : 'var(--pc-super)' }"
            >{{ pc }}</span>
            <span v-if="(selectedGroup.permissionCodes||[]).length === 0" class="pc-t-cap">暂无</span>
          </div>
        </div>
      </div>
    </el-drawer>

    <GroupFormDrawer
      v-model="formDrawerVisible"
      mode="create"
      :model="null"
      :rule-tree="ruleTree"
      @submit="handleCreateSubmit"
    />

  </main>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { Search, Plus, Close, Lock } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import ContactSelector  from '/@/components/ContactSelector.vue'
import GroupFormDrawer  from './components/GroupFormDrawer.vue'
import RbacAvatar       from '/@/components/rbac/RbacAvatar.vue'
import RbacBadge        from '/@/components/rbac/RbacBadge.vue'
import RbacStatusBadge  from '/@/components/rbac/RbacStatusBadge.vue'
import RbacProjectGlyph from '/@/components/rbac/RbacProjectGlyph.vue'
import RbacEmptyState   from '/@/components/rbac/RbacEmptyState.vue'
import RbacApiSource    from '/@/components/rbac/RbacApiSource.vue'
import {
  getGlobalGroups, getGlobalProjects, getGlobalUsers,
  updateGroupStatus,
  addGlobalGroupMember, removeGlobalGroupMember,
  getRuleTree,
  type GroupItem, type AdminItem, type RuleTreeNode,
} from '/@/api/backend/rbac'

/* ── Mock 人员（待替换） ── */
const MOCK_ORGS = [
  { id: 'root', pid: null, name: '总公司' },
  { id: 'tech', pid: 'root', name: '技术中心' },
]
const MOCK_USERS = [
  { id: '1', name: '张三', workNo: 'u001', phone: '13800000001', position: '工程师', orgId: 'tech' },
  { id: '2', name: '李四', workNo: 'u002', phone: '13800000002', position: '经理', orgId: 'tech' },
  { id: '3', name: '王五', workNo: 'u003', phone: '13800000003', position: '专员', orgId: 'tech' },
]

defineOptions({ name: 'backend/groups' })

/* ── 查询状态 ── */
const query = reactive({ keyword: '', project: '', status: '' as ''|'Active'|'Disabled', page: 1, pageSize: 20 })
const loading = ref(false)
const rows    = ref<GroupItem[]>([])
const total   = ref(0)
const projects = ref<string[]>([])

/* ── 详情 ── */
const drawerVisible   = ref(false)
const selectedGroup   = ref<GroupItem | null>(null)
const statusLoading   = ref(false)
const detailMembers   = ref<AdminItem[]>([])
const membersLoading  = ref(false)
const addMemberExpanded = ref(false)

/* ── 新建 ── */
const formDrawerVisible = ref(false)
const ruleTree = ref<RuleTreeNode[]>([])

/* ── 初始化 ── */
onMounted(async () => {
  const [, pRes] = await Promise.all([loadGroups(), getGlobalProjects(), loadRuleTree()])
  projects.value = pRes.list || []
})

async function loadGroups() {
  loading.value = true
  try {
    const res = await getGlobalGroups({
      keyword:  query.keyword  || undefined,
      project:  query.project  || undefined,
      status:   query.status   || undefined,
      page:     query.page,
      pageSize: query.pageSize,
    })
    rows.value  = res.list  || []
    total.value = res.total || 0
  } finally {
    loading.value = false
  }
}
function onSearch() { query.page = 1; loadGroups() }

/* ── 详情抽屉 ── */
async function openDetail(g: GroupItem) {
  selectedGroup.value   = g
  drawerVisible.value   = true
  addMemberExpanded.value = false
  membersLoading.value  = true
  try {
    const res = await getGlobalUsers({ project: g.project, page: 1, pageSize: 50 })
    // 过滤出属于该组的成员
    detailMembers.value = (res.list || []).filter(u => (u.groupCodes || []).includes(g.groupCode))
  } finally {
    membersLoading.value = false
  }
}

async function toggleStatus(active: boolean) {
  if (!selectedGroup.value) return
  statusLoading.value = true
  try {
    await updateGroupStatus(selectedGroup.value.groupCode, { status: active ? 'Active' : 'Disabled' })
    selectedGroup.value = { ...selectedGroup.value, status: active ? 'Active' : 'Disabled' }
    await loadGroups()
    ElMessage.success(`权限组已${active ? '启用' : '禁用'}`)
  } catch { ElMessage.error('操作失败') }
  finally { statusLoading.value = false }
}

async function onMemberConfirm(users: Array<{ workNo: string; name: string }>) {
  addMemberExpanded.value = false
  if (!selectedGroup.value || !users.length) return
  for (const u of users) {
    try {
      await addGlobalGroupMember(selectedGroup.value.groupCode, {
        userid: u.workNo,
        targetProject: selectedGroup.value.project,
      })
    } catch { ElMessage.warning(`${u.name} 添加失败`) }
  }
  ElMessage.success(`已添加 ${users.length} 名成员`)
  await openDetail(selectedGroup.value)
}

async function removeMember(userid: string) {
  if (!selectedGroup.value) return
  await ElMessageBox.confirm('确认移除该成员？', '移除成员', { type: 'warning' })
  try {
    await removeGlobalGroupMember(selectedGroup.value.groupCode, userid, selectedGroup.value.project)
    detailMembers.value = detailMembers.value.filter(u => u.userid !== userid)
    ElMessage.success('已移除')
  } catch { ElMessage.error('操作失败') }
}

/* ── 新建 ── */
function openCreate() {
  formDrawerVisible.value = true
}

async function loadRuleTree() {
  try {
    ruleTree.value = await getRuleTree()
  } catch {
    ruleTree.value = []
  }
}

async function handleCreateSubmit() {
  formDrawerVisible.value = false
  await loadGroups()
}
</script>

<style scoped lang="scss">
.pc-page {
  max-width: 1240px;
  min-height: calc(100vh - 60px);
  margin: 0 auto;
  padding: 30px 32px 80px;
  font-family: var(--pc-font-text);
  box-sizing: border-box;
}

.groups-toolbar {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 18px;
  flex-wrap: wrap;
}
.groups-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 14px;
  margin-bottom: 18px;
}
.group-card {
  text-align: left;
  display: flex;
  flex-direction: column;
  gap: 14px;
  padding: 20px;
  border-radius: 18px;
  border: 1px solid var(--pc-hairline);
  background: #fff;
  cursor: pointer;
  transition: border-color 0.15s, transform 0.08s;
  &:hover { transform: translateY(-1px); }
}
.group-card__top  { display: flex; align-items: flex-start; justify-content: space-between; }
.group-card__icon { width: 38px; height: 38px; border-radius: 11px; background: var(--pc-blue-wash); color: var(--pc-blue); display: flex; align-items: center; justify-content: center; }
.group-card__name { font-size: 15.5px; font-weight: 600; letter-spacing: -0.01em; }
.group-card__foot { display: flex; align-items: center; justify-content: space-between; }
.group-card__proj { display: inline-flex; align-items: center; gap: 6px; }

.groups-pagination { display: flex; align-items: center; justify-content: space-between; margin-top: 14px; flex-wrap: wrap; gap: 8px; }

/* Drawer */
.detail-drawer { display: flex; flex-direction: column; height: 100%; }
.detail-header  { display: flex; align-items: center; justify-content: space-between; padding: 22px 24px 18px; border-bottom: 1px solid var(--pc-divider); flex-shrink: 0; }
.detail-hero    { display: flex; align-items: center; gap: 13px; padding: 20px 24px 16px; border-bottom: 1px solid var(--pc-divider); flex-shrink: 0; }
.detail-hero__icon { width: 48px; height: 48px; border-radius: 13px; background: var(--pc-blue-wash); color: var(--pc-blue); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.detail-meta-row { display: flex; gap: 10px; padding: 14px 24px; border-bottom: 1px solid var(--pc-divider); flex-shrink: 0; }
.detail-meta-card { flex: 1; padding: 10px 12px; background: var(--pc-parchment); border-radius: 10px; }
.detail-body    { flex: 1; overflow-y: auto; padding: 20px 24px; }
.detail-section-card { display: flex; align-items: center; justify-content: space-between; padding: 12px 14px; background: var(--pc-parchment); border-radius: 12px; margin-bottom: 22px; }
.detail-section-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
.add-member-box { border: 1px solid var(--pc-hairline); border-radius: 12px; overflow: hidden; margin-bottom: 14px; max-height: 560px; }
.member-list { display: flex; flex-direction: column; gap: 7px; margin-bottom: 24px; }
.member-row  { display: flex; align-items: center; gap: 11px; padding: 9px 12px; border: 1px solid var(--pc-hairline); border-radius: 11px; }
.perm-chips  { display: flex; flex-wrap: wrap; gap: 7px; }
.perm-chip   { font-family: var(--pc-font-mono); font-size: 11.5px; padding: 5px 10px; border-radius: 7px; }

/* Create dialog */
.create-form { display: flex; flex-direction: column; gap: 18px; }
.create-form__grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
.form-field > label { display: block; font-size: 12px; font-weight: 600; color: var(--pc-ink-60); margin-bottom: 7px; }
.rule-select-box { border: 1px solid var(--pc-hairline); border-radius: 12px; max-height: 200px; overflow-y: auto; padding: 6px; }
.rule-select-item { display: flex; align-items: center; gap: 10px; padding: 7px 8px; cursor: pointer; border-radius: 8px; &:hover { background: var(--pc-parchment); } }
.extra-perm-chips { display: flex; flex-wrap: wrap; gap: 7px; }
.extra-chip { padding: 6px 11px; border-radius: 9999px; font-size: 12px; cursor: pointer; border: 1px solid var(--pc-hairline); background: #fff; color: var(--pc-ink-80); transition: all 0.12s; &--on { border: 1.5px solid var(--pc-blue); background: var(--pc-blue-wash); color: var(--pc-blue); } }
.derived-preview { background: var(--pc-parchment); border-radius: 12px; padding: 14px; }
</style>

// prototype/pc/groups.jsx
/* ============================================================
   Permission group management.
   APIs: GET /api/global/group/list, GET /api/group/list,
         POST /api/group, PUT /api/group/{groupCode}/status,
         POST /api/global/group/{groupCode}/members,
         DELETE /api/global/group/{groupCode}/members/{userid}?targetProject=
         GET /api/rule/tree, GET /api/api-map/list
   ============================================================ */
const { useState: useSG, useEffect: useEffG } = React;

function GroupDetail({ group, ctx, onClose }) {
  const { store, actions } = ctx;
  const g = store.groups.find(x => x.groupCode === group.groupCode) || group;
  const p = store.projects.find(x => x.code === g.project);
  const members = store.users.filter(u => u.groupCodes.includes(g.groupCode));
  const [adding, setAdding] = useSG(false);
  const [kw, setKw] = useSG("");
  const candidates = store.users.filter(u => !u.groupCodes.includes(g.groupCode) && (u.username.includes(kw) || u.userid.toLowerCase().includes(kw.toLowerCase())));

  return (
    <React.Fragment>
      <div style={{ padding: "22px 24px 18px", borderBottom: "1px solid var(--divider)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
          <span className="t-cap-strong">权限组详情</span>
          <button className="btn" onClick={onClose} style={{ width: 32, height: 32, borderRadius: 8, background: "var(--parchment)" }}><Icon name="x" size={17} /></button>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 13 }}>
          <span style={{ width: 48, height: 48, borderRadius: 13, background: "var(--blue-wash)", color: "var(--blue)", display: "flex", alignItems: "center", justifyContent: "center" }}><Icon name="shield" size={24} /></span>
          <div style={{ flex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
              <span className="t-title" style={{ fontSize: 21 }}>{g.groupName}</span>
              <Badge tone={g.status === "Active" ? "ok" : "neutral"} dot size="sm">{g.status === "Active" ? "启用" : "禁用"}</Badge>
            </div>
            <div className="t-cap" style={{ marginTop: 2 }}><span className="t-mono">{g.groupCode}</span></div>
          </div>
        </div>
        <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
          <div style={{ flex: 1, padding: "10px 12px", background: "var(--parchment)", borderRadius: 10, display: "flex", alignItems: "center", gap: 9 }}>
            <ProjectGlyph code={g.project} name={p ? p.name : g.project} size={26} />
            <div><div className="t-cap" style={{ fontSize: 11 }}>所属系统</div><div className="t-body-strong" style={{ fontSize: 13 }}>{p ? p.name : g.project}</div></div>
          </div>
          <div style={{ flex: 1, padding: "10px 12px", background: "var(--parchment)", borderRadius: 10 }}>
            <div className="t-cap" style={{ fontSize: 11 }}>父权限组</div>
            <div className="t-body-strong" style={{ fontSize: 13 }}>{g.parent_group_code || "根组"}</div>
          </div>
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", padding: "20px 24px" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 14px", background: "var(--parchment)", borderRadius: 12, marginBottom: 22 }}>
          <div><div className="t-body-strong" style={{ fontSize: 14 }}>启用状态</div><div className="t-cap">PUT /api/group/{"{groupCode}"}/status</div></div>
          <Toggle on={g.status === "Active"} onChange={(v) => actions.setGroupStatus(g.groupCode, v ? "Active" : "Disabled")} />
        </div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}>
          <span className="t-section">成员（{members.length}）</span>
          <button className="btn btn-text" onClick={() => setAdding(a => !a)}><Icon name="plus" size={14} /> 添加成员</button>
        </div>
        {adding && (
          <div className="anim-fade" style={{ border: "1px solid var(--hairline)", borderRadius: 12, padding: 12, marginBottom: 14 }}>
            <SearchInput value={kw} onChange={setKw} placeholder={`搜索用户加入 ${g.project}`} width="100%" />
            <div style={{ maxHeight: 200, overflowY: "auto", marginTop: 10 }}>
              {candidates.slice(0, 8).map(u => (
                <div key={u.userid} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 4px", borderTop: "1px solid var(--divider)" }}>
                  <Avatar name={u.username} size={28} />
                  <div style={{ flex: 1 }}><span className="t-body-strong" style={{ fontSize: 13 }}>{u.username}</span> <span className="t-cap"><span className="t-mono" style={{ fontSize: 11 }}>{u.userid}</span></span></div>
                  <button className="btn btn-ghost btn-sm" onClick={() => actions.addMember(g.groupCode, u.userid, g.project, u.username)}>加入</button>
                </div>
              ))}
              {candidates.length === 0 && <div className="t-cap" style={{ padding: 10, textAlign: "center" }}>无可添加用户</div>}
            </div>
          </div>
        )}
        <div style={{ display: "flex", flexDirection: "column", gap: 7, marginBottom: 24 }}>
          {members.map(u => (
            <div key={u.userid} style={{ display: "flex", alignItems: "center", gap: 11, padding: "9px 12px", border: "1px solid var(--hairline)", borderRadius: 11 }}>
              <Avatar name={u.username} size={30} dim={u.status === "Disabled"} />
              <div style={{ flex: 1 }}><div className="t-body-strong" style={{ fontSize: 13.5 }}>{u.username}</div><div className="t-cap"><span className="t-mono" style={{ fontSize: 11 }}>{u.userid}</span></div></div>
              <button className="btn" onClick={() => actions.removeMember(g.groupCode, u.userid)} title="移除"
                style={{ width: 28, height: 28, borderRadius: 8, color: "var(--deny)", background: "var(--deny-wash)" }}><Icon name="x" size={15} /></button>
            </div>
          ))}
          {members.length === 0 && <div className="t-cap" style={{ padding: "6px 0" }}>暂无成员</div>}
        </div>

        <div className="t-section" style={{ marginBottom: 4 }}>授权权限码（{g.permissionCodes.length}）</div>
        <div className="t-cap" style={{ marginBottom: 12 }}>permissionCodes = ruleCodes 推导值 ∪ extraPermissionCodes</div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>
          {g.permissionCodes.map(pc => (
            <span key={pc} className="t-mono" style={{ fontSize: 11.5, padding: "5px 10px", background: pc.startsWith("menu:") ? "#eef4fb" : "#f3eefb",
              color: pc.startsWith("menu:") ? "var(--blue)" : "var(--super)", borderRadius: 7 }}>{pc}</span>
          ))}
        </div>
      </div>
    </React.Fragment>
  );
}

function CreateGroupModal({ ctx, onClose }) {
  const { store, actions } = ctx;
  const [name, setName] = useSG("");
  const [code, setCode] = useSG("");
  const [project, setProject] = useSG(store.projects[0].code);
  const [parent, setParent] = useSG("");
  const [ruleCodes, setRuleCodes] = useSG([]);
  const [extra, setExtra] = useSG([]);

  const flatten = (nodes, out = []) => { (nodes||[]).forEach(n => { out.push(n); if (n.children) flatten(n.children, out); }); return out; };
  const rules = flatten(store.ruleTree[project] || []);
  const projGroups = store.groups.filter(g => g.project === project);
  const toggleRule = (rc) => setRuleCodes(s => s.includes(rc) ? s.filter(x => x !== rc) : [...s, rc]);
  const toggleExtra = (pc) => setExtra(s => s.includes(pc) ? s.filter(x => x !== pc) : [...s, pc]);

  const derived = Array.from(new Set([
    ...rules.filter(r => ruleCodes.includes(r.ruleCode)).map(r => r.permissionCode),
    ...extra,
  ]));

  const submit = () => {
    actions.createGroup({
      groupCode: code || ("group_" + Math.random().toString(36).slice(2, 8)),
      groupName: name || "未命名组", project, parent_group_code: parent || null, status: "Active",
      permissionCodes: derived,
    });
    onClose();
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", maxHeight: "86vh" }}>
      <div style={{ padding: "22px 26px 16px", borderBottom: "1px solid var(--divider)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div><div className="t-title" style={{ fontSize: 21 }}>新建权限组</div><div className="t-cap" style={{ marginTop: 2 }}>POST /api/group</div></div>
        <button className="btn" onClick={onClose} style={{ width: 32, height: 32, borderRadius: 8, background: "var(--parchment)" }}><Icon name="x" size={17} /></button>
      </div>
      <div style={{ flex: 1, overflowY: "auto", padding: 26, display: "flex", flexDirection: "column", gap: 18 }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}>
          <Field label="组名称" value={name} onChange={setName} placeholder="例如 门户管理员" />
          <Field label="组编码 groupCode" value={code} onChange={setCode} placeholder="留空自动生成 group_<guid>" mono />
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}>
          <Field label="所属系统 project" as="select" value={project} onChange={(v) => { setProject(v); setRuleCodes([]); setParent(""); }}>
            {store.projects.map(p => <option key={p.code} value={p.code}>{p.name}</option>)}
          </Field>
          <Field label="父权限组" as="select" value={parent} onChange={setParent}>
            <option value="">根组（无父级）</option>
            {projGroups.map(g => <option key={g.groupCode} value={g.groupCode}>{g.groupName}</option>)}
          </Field>
        </div>
        <div>
          <div className="t-cap-strong" style={{ marginBottom: 8 }}>规则授权 ruleCodes · GET /api/rule/tree</div>
          <div style={{ border: "1px solid var(--hairline)", borderRadius: 12, maxHeight: 200, overflowY: "auto", padding: 6 }}>
            {rules.map(r => (
              <label key={r.ruleCode} style={{ display: "flex", alignItems: "center", gap: 10, padding: "7px 8px", cursor: "pointer", borderRadius: 8 }}>
                <Check on={ruleCodes.includes(r.ruleCode)} onChange={() => toggleRule(r.ruleCode)} />
                <span style={{ paddingLeft: r.type === "Button" ? 16 : 0, display: "flex", alignItems: "center", gap: 7, flex: 1 }}>
                  <Badge tone={r.type === "Button" ? "neutral" : r.type === "MenuDir" ? "blue" : "ok"} size="sm">{r.type}</Badge>
                  <span className="t-body" style={{ fontSize: 13 }}>{r.title}</span>
                  <span className="t-mono muted" style={{ fontSize: 11, marginLeft: "auto" }}>{r.permissionCode}</span>
                </span>
              </label>
            ))}
          </div>
        </div>
        <div>
          <div className="t-cap-strong" style={{ marginBottom: 8 }}>追加端点权限 extraPermissionCodes · GET /api/api-map/list</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>
            {store.permView.map(pv => {
              const on = extra.includes(pv.permissionCode);
              return (
                <button key={pv.permissionCode} className="btn" onClick={() => toggleExtra(pv.permissionCode)}
                  style={{ padding: "6px 11px", borderRadius: 9999, fontSize: 12,
                    border: on ? "1.5px solid var(--blue)" : "1px solid var(--hairline)", background: on ? "var(--blue-wash)" : "#fff", color: on ? "var(--blue)" : "var(--ink-80)" }}>
                  <span className="t-mono" style={{ fontSize: 11.5 }}>{pv.permissionCode}</span>
                </button>
              );
            })}
          </div>
        </div>
        <div style={{ background: "var(--parchment)", borderRadius: 12, padding: 14 }}>
          <div className="t-cap-strong" style={{ marginBottom: 8 }}>最终授权权限码（{derived.length}）</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {derived.length === 0 ? <span className="t-cap">尚未选择任何规则或端点权限</span> : derived.map(d => <span key={d} className="t-mono" style={{ fontSize: 11, padding: "3px 8px", background: "#fff", borderRadius: 6 }}>{d}</span>)}
          </div>
        </div>
      </div>
      <div style={{ padding: "16px 26px", borderTop: "1px solid var(--divider)", display: "flex", justifyContent: "flex-end", gap: 10 }}>
        <button className="btn btn-neutral" onClick={onClose}>取消</button>
        <button className="btn btn-primary" onClick={submit}>创建权限组</button>
      </div>
    </div>
  );
}

function GroupsPage({ ctx, setAction }) {
  const { store, intent } = ctx;
  const [kw, setKw] = useSG("");
  const [proj, setProj] = useSG(intent && intent.project ? intent.project : "all");
  const [sel, setSel] = useSG(null);
  const [creating, setCreating] = useSG(false);

  useEffG(() => {
    setAction(<button className="btn btn-primary" onClick={() => setCreating(true)}><Icon name="plus" size={16} /> 新建权限组</button>);
    return () => setAction(null);
  }, []);

  const rows = store.groups.filter(g => {
    if (proj !== "all" && g.project !== proj) return false;
    if (kw && !(g.groupName.includes(kw) || g.groupCode.toLowerCase().includes(kw.toLowerCase()))) return false;
    return true;
  });

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 18, flexWrap: "wrap" }}>
        <SearchInput value={kw} onChange={setKw} placeholder="搜索组名或编码" width={240} />
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 }}>
          <Icon name="filter" size={15} style={{ color: "var(--ink-48)" }} />
          <select value={proj} onChange={e => setProj(e.target.value)} style={{ height: 34, borderRadius: 9999, border: "1px solid var(--hairline)", background: "#fff", padding: "0 14px", fontSize: 13.5 }}>
            <option value="all">全部系统</option>
            {store.projects.map(p => <option key={p.code} value={p.code}>{p.name}</option>)}
          </select>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 14 }}>
        {rows.map(g => {
          const p = store.projects.find(x => x.code === g.project);
          return (
            <button key={g.groupCode} className="btn" onClick={() => setSel(g)}
              style={{ textAlign: "left", flexDirection: "column", alignItems: "stretch", gap: 14, padding: 20, borderRadius: 18, border: "1px solid var(--hairline)", background: "#fff" }}
              onMouseEnter={e => e.currentTarget.style.borderColor = "#cdcdd2"} onMouseLeave={e => e.currentTarget.style.borderColor = "var(--hairline)"}>
              <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between" }}>
                <span style={{ width: 38, height: 38, borderRadius: 11, background: "var(--blue-wash)", color: "var(--blue)", display: "flex", alignItems: "center", justifyContent: "center" }}><Icon name="shield" size={20} /></span>
                <Badge tone={g.status === "Active" ? "ok" : "neutral"} dot size="sm">{g.status === "Active" ? "启用" : "禁用"}</Badge>
              </div>
              <div>
                <div className="t-body-strong" style={{ fontSize: 15.5 }}>{g.groupName}</div>
                <div className="t-cap" style={{ marginTop: 2 }}><span className="t-mono" style={{ fontSize: 11.5 }}>{g.groupCode}</span></div>
              </div>
              <hr className="hr" style={{ background: "var(--divider)" }} />
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <span style={{ display: "inline-flex", alignItems: "center", gap: 6 }}><ProjectGlyph code={g.project} name={p ? p.name : g.project} size={20} radius={5} /><span className="t-cap" style={{ fontWeight: 500 }}>{p ? p.name.replace(" Center","") : g.project}</span></span>
                <span className="t-cap"><b style={{ color: "var(--ink)" }}>{g.members}</b> 成员 · <b style={{ color: "var(--ink)" }}>{g.permissionCodes.length}</b> 权限码</span>
              </div>
            </button>
          );
        })}
      </div>
      {rows.length === 0 && <div className="card" style={{ padding: 50, textAlign: "center" }}><span className="t-cap">无匹配权限组</span></div>}

      <div className="t-cap" style={{ marginTop: 14 }}>显示 {rows.length} 个权限组 · 全局合计 {store.stats.groups} 个</div>

      <div style={{ marginTop: 22 }}>
        <ApiSource endpoints={[
          { m: "GET", p: "/api/global/group/list", d: "跨 project 权限组列表" },
          { m: "POST", p: "/api/group", d: "新建权限组（ruleCodes + extraPermissionCodes）" },
          { m: "PUT", p: "/api/group/{groupCode}/status", d: "启用 / 禁用" },
          { m: "POST", p: "/api/global/group/{groupCode}/members", d: "加入成员（body 含 targetProject）" },
          { m: "DELETE", p: "/api/global/group/{groupCode}/members/{userid}", d: "移除成员（query targetProject）" },
          { m: "GET", p: "/api/rule/tree", d: "规则授权选择器" },
        ]} note="组层级仅用于展示，实际访问由 permissionCodes 决定。组的新建/编辑为 per-project 接口；跨 project 组模板为建议的未来扩展。" />
      </div>

      <Drawer open={!!sel} onClose={() => setSel(null)} width={470}>{sel && <GroupDetail group={sel} ctx={ctx} onClose={() => setSel(null)} />}</Drawer>
      <Modal open={creating} onClose={() => setCreating(false)} width={620}>{creating && <CreateGroupModal ctx={ctx} onClose={() => setCreating(false)} />}</Modal>
    </div>
  );
}

window.GroupsPage = GroupsPage;
